DEFAULT_DATASET: str = "property_search"
DEFAULT_TABLE: str = "austin_housing"
DEFAULT_VECTOR_DIMENSION: int = 768
DEFAULT_TASK_TYPE: str = "SEMANTIC_SIMILARITY"
DEFAULT_DISTANCE_TYPE: str = "COSINE"
MAX_TOP_K: int = 100
